[project]
name = "kratopdf"
version = "0.1.0"
description = "Stack all kra into the kra folder and export them into pdf"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "image>=1.5.33",
]
